[package]
name = "processor_rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "processor_rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21", features = ["extension-module"] }

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
